#!/usr/bin/env python

import argparse
import sys
# prep python path for base module
sys.path.append('./core/')
import base

def recon_cli(args):
    x = base.Recon(mode=1)
    # set the given workspace
    if args.workspace: x.do_workspace(args.workspace)
    # set given global options
    for option in args.goptions:
        param = ' '.join(option.split('='))
        x.do_set(param)
    # if requested, show global options and exit
    if args.gshow:
        x.do_show('options')
        return
    # if requested, show modules and exit
    if args.show_modules:
        x.do_show('modules')
        return
    # exit if module not specified
    if not args.module:
        print('%s[!] Module required.%s' % (R, N))
        return
    # load the module
    y = x.do_load(args.module)
    # exit if module not successfully loaded
    if not y: return
    # set given module options
    for option in args.options:
        param = ' '.join(option.split('='))
        y.do_set(param)
    # if requested, show module options and exit
    if args.show:
        y.do_show('options')
        return
    # run the module
    y.do_run(None)

description = '%%(prog)s - %s %s' % (base.__author__, base.__email__)
parser = argparse.ArgumentParser(description=description, version=base.__version__)
parser.add_argument('-w', help='load/create a workspace', metavar='workspace', dest='workspace', action='store')
parser.add_argument('-G', help='show available global options', dest='gshow', default=False, action='store_true')
parser.add_argument('-g', help='set a global option (can be used more than once)', metavar='name=value', dest='goptions', default=[], action='append')
parser.add_argument('-M', help='show modules', dest='show_modules', default=False, action='store_true')
parser.add_argument('-m', help='specify the module', metavar='module', dest='module', action='store')
parser.add_argument('-O', help='show available module options', dest='show', default=False, action='store_true')
parser.add_argument('-o', help='set a module option (can be used more than once)', metavar='name=value', dest='options', default=[], action='append')
args = parser.parse_args()
recon_cli(args)
